[package]
name = "speedrun-survivors-bevy"
version.workspace = true
edition.workspace = true
default-run = "speedrun-survivors-bevy"

[dependencies]
anyhow.workspace = true
bevy = { version = "0.11", features = ["dynamic_linking"] }
bevy_editor_pls = "0.6"
bevy_ecs_ldtk = "0.8"
rand.workspace = true
