[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Closed Source; All rights reserved"
license-file = "LICENSE.md"


[workspace]
resolver = "2"
members = ["speedrun-survivors-bevy", "speedrun-survivors-api"]


[workspace.dependencies]
anyhow = "1"
rand = "0.8"
